---
- hosts: all
  become: true
  tasks:
    - name: Change port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: "^Listen 90"
        line: "Listen 80"
      notify: Restart apache

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted